Document: vdr-plugin-restfulapi
Title: Debian vdr-plugin-restfulapi Manual
Author: <insert document author here>
Abstract: This manual describes what vdr-plugin-restfulapi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vdr-plugin-restfulapi/vdr-plugin-restfulapi.sgml.gz

Format: postscript
Files: /usr/share/doc/vdr-plugin-restfulapi/vdr-plugin-restfulapi.ps.gz

Format: text
Files: /usr/share/doc/vdr-plugin-restfulapi/vdr-plugin-restfulapi.text.gz

Format: HTML
Index: /usr/share/doc/vdr-plugin-restfulapi/html/index.html
Files: /usr/share/doc/vdr-plugin-restfulapi/html/*.html
